[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comic-analytics"
version = "0.1.0"
description = "Comic analytics desktop app"
requires-python = ">=3.8"
dependencies = ["PySide6"]

[tool.setuptools.packages.find]
where = ["src"]
